//
//  Gradients.swift
//  Gradients
//
//  Created by Cruz on 30/09/2018.
//  Copyright © 2018 Cruz. All rights reserved.
//

public enum Gradients: Int, CaseIterable {
    case warmFlame = 1
    case nightFade
    case springWarmth
    case juicyPeach
    case youngPassion
    case ladyLips
    case sunnyMorning
    case rainyAshville
    case frozenDreams
    case winterNeva
    case dustyGrass
    case temptingAzure
    case heavyRain
    case amyCrisp
    case meanFruit
    case softBlue
    case ripeMalinka
    case cloudyKnoxville
    case malibuBeach
    case newLife
    case trueSunset
    case morpheusDen
    case rareWind
    case nearMoon
    case wildApple
    case saintPetersburg
    case ariellesSmile
    case plumPlate
    case everlastingSky
    case happyFisher
    case blessing
    case sharpeyeEagle
    case ladogaBottom
    case lemonGate
    case itmeoBranding
    case zeusMiracle
    case oldHat
    case starWine
    case deepBlue
    case coupDeGrace
    case happyAcid
    case awesomePine
    case newYork
    case shyRainbow
    case loonCrest
    case mixedHopes
    case flyHigh
    case strongBliss
    case freshMilk
    case snowAgain
    case februaryInk
    case kindSteel
    case softGrass
    case grownEarly
    case sharpBlues
    case shadyWater
    case dirtyBeauty
    case greatWhale
    case teenNotebook
    case politeRumors
    case sweetPeriod
    case wideMatrix
    case softCherish
    case redSalvation
    case burningSpring
    case nightParty
    case skyGlider
    case heavenPeach
    case purpleDivision
    case aquaSplash
    case aboveClouds
    case spikyNaga
    case loveKiss
    case sharpGlass
    case cleanMirror
    case premiumDark
    case coldEvening
    case cochitiLake
    case summerGames
    case passionateBed
    case mountainRock
    case desertHump
    case jungleDay
    case phoenixStart
    case octoberSilence
    case farawayRiver
    case alchemistLab
    case overSun
    case premiumWhite
    case marsParty
    case eternalConstance
    case japanBlush
    case smilingRain
    case cloudyApple
    case bigMango
    case healthyWater
    case amourAmour
    case riskyConcrete
    case strongStick
    case viciousStance
    case paloAlto
    case happyMemories
    case midnightBloom
    case crystalline
    case raccoonBack
    case partyBliss
    case confidentCloud
    case leCocktail
    case riverCity
    case frozenBerry
    case elegance
    case childCare
    case flyingLemon
    case newRetrowave
    case hiddenJaguar
    case aboveTheSky
    case nega
    case denseWater
    case chemicAqua
    case seashore
    case marbleWall
    case cheerfulCaramel
    case nightSky
    case magicLake
    case youngGrass
    case colorfulPeach
    case gentleCare
    case plumBath
    case happyUnicorn
    case fullMetal
    case africanField
    case solidStone
    case orangeJuice
    case glassWater
    case slickCarbon
    case northMiracle
    case fruitBlend
    case millenniumPine
    case highFlight
    case moleHall
    case earlGray
    case spaceShift
    case forestInei
    case royalGarden
    case richMetal
    case juicyCake
    case smartIndigo
    case sandStrike
    case norseBeauty
    case aquaGuidance
    case sunVeggie
    case seaLord
    case blackSea
    case grassShampoo
    case landingAircraft
    case witchDance
    case sleeplessNight
    case angelCare
    case crystalRiver
    case softLipstick
    case saltMountain
    case perfectWhite
    case freshOasis
    case strictNovember
    case morningSalad
    case deepRelief
    case seaStrike
    case nightCall
    case supremeSky
    case lightBlue
    case mindCrawl
    case lilyMeadow
    case sugarLollipop
    case sweetDessert
    case magicRay
    case teenParty
    case frozenHeat
    case gagarinView
    case fabledSunset
    case perfectBlue
}
